### PR TITLE
Added an Aimbot, a Velocity mod, and a Criticals mod, organized the imports, and made certain mods disable on death.

### PR DESCRIPTION
**Pull request by eric-mcdonald**
So I don't see sh*t like this on HF anymore: http://www.hackforums.net/showthread.php?tid=4814020 <-- PLEASE! MAKE IT STOP!

Kthnxbai,

pootPoot

### CODE REVIEW

**Comment by 101010101010101010** [comment]
needs to be added tbh

**Comment by brudin** [comment]
What is the onPlayerClone for?

**Comment by eric-mcdonald** [comment]
@brudin , onPlayerClone is to tell when the player has respawned. It's there to disable certain mods (Aimbot and TriggerBot) when the player dies.

Edit: if you mean why it handles both a WorldEvent#Unload and PlayerEvent#Clone, it's because the world isn't unloaded when you respawn, it seems.

**Comment by corrupt3d** [comment]
This should really be added.

**Comment by CircleStrafe** [comment]
Link to client with the aimbot?

**Comment by eric-mcdonald** [comment]
@CircleStrafe I'm not sure if I'm allowed to deploy unofficial updates of Scooby. If I'm allowed to, I will probably post a compiled JAR file of my version of Scooby that contains an Aimbot. I also just added a Velocity mod (reduces your velocity by random amounts). Kek.

**Comment by corrupt3d** [comment]
@gunrun66 Im pretty sure you are allowed to make your own version. From what i understand from the description of this client. It would be nice if he added it to his aswell, but I want it now xD
A free and open source 'ghost client'.

You are not to use any of the code provided in this mod for your own monetary gain, nor are you allowed to use any code provided in this mod without given credit and permission. You are free to use and modify it for personal use, feel free to fork this repo and have fun. Same rules go for the client jar itself; do not use anything here to make money.

**Comment by brudin** [comment]
@gunrun66 Feel free to distribute your version of the mod.  As long as you're not making any money off it, I don't really mind. :ghost:

**Comment by eric-mcdonald** [comment]
@brudin alright, thanks for letting me know. I'm probably going to close this pull request and develop my fork of Scooby as a ghost client that is based off of Scooby.

**Pull request closed without merging**
